### ISSUE TITLE
expected 0 arguments, but got 1

### ISSUE THREAD

**Issue by abcd-ca** [oguimbal/moment-deno#1]
![image](https://user-images.githubusercontent.com/1296103/106396630-ff696c80-63bd-11eb-8a97-188977cac8ea.png)

I can run my app and moment is working but Webstorm, even with the Deno plugin is confused about the arguments. Any ideas?

**Comment by oguimbal** [comment]
I'm not quite sure how to help you, as I dont use Webstorm 🤐

Type checking is OK with vscode ... are you using the right import ?
![image](https://user-images.githubusercontent.com/8973947/106453499-b7178080-6489-11eb-873a-f140c471ba12.png)

**Comment by abcd-ca** [comment]
Fair enough! My code compiles and runs fine so I think you can close this issue and I will inquire with Webstorm. Thanks!

**Comment by oguimbal** [comment]
No problem :)

If you find the solution, dont hesistate to post it here (might be useful to others, who knows)

**Comment by abcd-ca** [comment]
Created issue in WebStorm issue tracker: https://youtrack.jetbrains.com/issue/WEB-49396
